import { Router } from 'express';
import { authRouter } from '../modules/auth/auth.routes.js';
import { patientsRouter } from '../modules/patients/patients.routes.js';
import { doctorsRouter } from '../modules/doctors/doctors.routes.js';
import { receptionistsRouter } from '../modules/receptionists/receptionists.routes.js';
import { investigationsRouter } from '../modules/investigations/investigations.routes.js';
import { bedManagementRouter } from '../modules/bedManagement/bed.routes.js';
import { appointmentsRouter } from '../modules/appointments/appointments.routes.js';
import { billsRouter } from '../modules/bills/bills.routes.js';
import { activitiesRouter } from '../modules/activities/activities.routes.js';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes.js';
import { hospitalSettingsRouter } from '../modules/hospitalSettings/hospitalSettings.routes.js';
import { reportsRouter } from '../modules/reports/reports.routes.js';
import { consultationsRouter } from '../modules/consultations/consultations.routes.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/patients', patientsRouter);
apiRouter.use('/doctors', doctorsRouter);
apiRouter.use('/receptionists', receptionistsRouter);
apiRouter.use('/investigations', investigationsRouter);
apiRouter.use('/bed-management', bedManagementRouter);
apiRouter.use('/appointments', appointmentsRouter);
apiRouter.use('/bills', billsRouter);
apiRouter.use('/activities', activitiesRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/hospital-settings', hospitalSettingsRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/consultations', consultationsRouter);
