export const INITIAL_APPOINTMENTS = [
  {
    id: 'APT001',
    patientId: 'PT001245',
    patientName: 'Ramesh Babu',
    doctorId: 'DOC001',
    doctorName: 'Dr. Arjun Kumar',
    date: '2026-06-21',
    time: '10:30 AM',
    type: 'Consultation',
    status: 'Checked In',
    priority: 'Emergency',
    chiefComplaint: 'Severe right knee joint pain and swelling for 2 weeks',
    fee: 500
  },
  {
    id: 'APT002',
    patientId: 'PT001244',
    patientName: 'Anjali Kumari',
    doctorId: 'DOC002',
    doctorName: 'Dr. Priya Smith',
    date: '2026-06-21',
    time: '11:00 AM',
    type: 'Therapy',
    status: 'Scheduled',
    priority: 'Routine',
    chiefComplaint: 'Acute left knee instability',
    fee: 600
  },
  {
    id: 'APT003',
    patientId: 'PT001243',
    patientName: 'Mohan Rao',
    doctorId: 'DOC001',
    doctorName: 'Dr. Arjun Kumar',
    date: '2026-06-21',
    time: '09:30 AM',
    type: 'Consultation',
    status: 'In Consultation',
    priority: 'Emergency',
    chiefComplaint: 'Inability to bear weight on left hip after a fall',
    fee: 500
  },
  {
    id: 'APT004',
    patientId: 'PT001242',
    patientName: 'Kanya Sree',
    doctorId: 'DOC005',
    doctorName: 'Dr. Mahesh Babu',
    date: '2026-06-20',
    time: '10:00 AM',
    type: 'Follow Up',
    status: 'Completed',
    priority: 'Follow-up',
    chiefComplaint: 'Tingling and numbness in right hand fingers',
    fee: 300
  },
  {
    id: 'APT005',
    patientId: 'PT001241',
    patientName: 'Srinivas Reddy',
    doctorId: 'DOC001',
    doctorName: 'Dr. Arjun Kumar',
    date: '2026-06-21',
    time: '11:30 AM',
    type: 'Consultation',
    status: 'Scheduled',
    priority: 'Follow-up',
    chiefComplaint: 'Lower back pain and radiating sciatica',
    fee: 500
  },
  {
    id: 'APT006',
    patientId: 'PT001240',
    patientName: 'Prasad Rao',
    doctorId: 'DOC001',
    doctorName: 'Dr. Arjun Kumar',
    date: '2026-06-19',
    time: '04:00 PM',
    type: 'Consultation',
    status: 'Cancelled',
    priority: 'Routine',
    chiefComplaint: 'Frozen right shoulder stiffness',
    fee: 500
  },
  {
    id: 'APT007',
    patientId: 'PT001242',
    patientName: 'Kanya Sree',
    doctorId: 'DOC001',
    doctorName: 'Dr. Arjun Kumar',
    date: '2026-06-21',
    time: '12:00 PM',
    type: 'Follow Up',
    status: 'Scheduled',
    priority: 'Routine',
    chiefComplaint: 'Follow-up on carpal tunnel splint check',
    fee: 300
  },
  {
    id: 'APT008',
    patientId: 'PT001240',
    patientName: 'Prasad Rao',
    doctorId: 'DOC001',
    doctorName: 'Dr. Arjun Kumar',
    date: '2026-06-21',
    time: '12:30 PM',
    type: 'Consultation',
    status: 'Checked In',
    priority: 'Emergency',
    chiefComplaint: 'Severe pain in right shoulder, sudden onset',
    fee: 500
  },
  {
    id: 'APT009',
    patientId: 'PT001239',
    patientName: 'Lalitha Kumari',
    doctorId: 'DOC001',
    doctorName: 'Dr. Arjun Kumar',
    date: '2026-06-21',
    time: '01:00 PM',
    type: 'Follow Up',
    status: 'Scheduled',
    priority: 'Routine',
    chiefComplaint: 'Checkup for left ankle sprain healing progress',
    fee: 300
  }
];
