export const INITIAL_PATIENTS = [
  {
    id: 'PT001245',
    name: 'Ramesh Babu',
    age: 45,
    gender: 'Male',
    phone: '9876543210',
    lastVisit: '12 May 2026',
    address: 'Rajahmundry, Danavaipeta',
    bloodGroup: 'O+',
    disease: 'Osteoarthritis Knee',
    registrationDate: '2026-06-21',
    chiefComplaint: 'Severe right knee joint pain and swelling for 2 weeks, difficulty walking.',
    allergies: 'Penicillin, Peanuts',
    currentMedications: 'Tab. Paracetamol 650mg BD, Tab. Pantocid 40mg OD',
    pastMedicalHistory: 'Hypertension (diagnosed 2022), Knee arthroscopy (2024)',
    photoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Ramesh+Babu'
  },
  {
    id: 'PT001244',
    name: 'Anjali Kumari',
    age: 29,
    gender: 'Female',
    phone: '9551224567',
    lastVisit: '11 May 2026',
    address: 'Rajahmundry, Tilak Road',
    bloodGroup: 'B+',
    disease: 'Ligament Tear ACL',
    registrationDate: '2026-06-20',
    chiefComplaint: 'Acute instability and sharp pain in left knee after twisting injury.',
    allergies: 'None',
    currentMedications: 'Tab. Ultracet SOS, Tab. Chymoral Forte TID',
    pastMedicalHistory: 'None',
    photoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Anjali+Kumari'
  },
  {
    id: 'PT001243',
    name: 'Mohan Rao',
    age: 60,
    gender: 'Male',
    phone: '9701122334',
    lastVisit: '10 May 2026',
    address: 'Kakinada, Bhanugudi',
    bloodGroup: 'A+',
    disease: 'Hip Fracture',
    registrationDate: '2026-06-19',
    chiefComplaint: 'Inability to bear weight on left hip after a fall in the bathroom.',
    allergies: 'Sulfa Drugs',
    currentMedications: 'Tab. Amlodipine 5mg OD, Tab. Clopidogrel 75mg OD',
    pastMedicalHistory: 'Coronary Artery Disease (Stent placed 2021), Mild COPD',
    photoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Mohan+Rao'
  },
  {
    id: 'PT001242',
    name: 'Kanya Sree',
    age: 38,
    gender: 'Female',
    phone: '7034561230',
    lastVisit: '09 May 2026',
    address: 'Rajahmundry, Lalacheruvu',
    bloodGroup: 'AB+',
    disease: 'Carpal Tunnel Syndrome',
    registrationDate: '2026-06-18',
    chiefComplaint: 'Numbness and tingling in right thumb, index, and middle fingers, worse at night.',
    allergies: 'None',
    currentMedications: 'Tab. Neurobion Forte OD',
    pastMedicalHistory: 'Hypothyroidism (on Thyronorm 50mcg)',
    photoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Kanya+Sree'
  },
  {
    id: 'PT001241',
    name: 'Srinivas Reddy',
    age: 52,
    gender: 'Male',
    phone: '9911223344',
    lastVisit: '08 May 2026',
    address: 'Ravulapalem, Main Bazar',
    bloodGroup: 'O-',
    disease: 'Lumbar Spondylosis',
    registrationDate: '2026-06-15',
    chiefComplaint: 'Chronic lower back pain radiating down to the left leg (sciatica) for 3 months.',
    allergies: 'NSAIDs (causes rash)',
    currentMedications: 'Tab. Gabapentin 100mg HS, Tab. Pregabalin 75mg OD',
    pastMedicalHistory: 'Type 2 Diabetes (on Metformin 500mg BD)',
    photoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Srinivas+Reddy'
  },
  {
    id: 'PT001240',
    name: 'Prasad Rao',
    age: 47,
    gender: 'Male',
    phone: '9392828282',
    lastVisit: '06 May 2026',
    address: 'Rajahmundry, Morampudi',
    bloodGroup: 'A-',
    disease: 'Frozen Shoulder',
    registrationDate: '2026-06-10',
    chiefComplaint: 'Progressive stiffness and severe pain in right shoulder, restricted abduction.',
    allergies: 'None',
    currentMedications: 'None',
    pastMedicalHistory: 'Dyslipidemia',
    photoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Prasad+Rao'
  },
  {
    id: 'PT001239',
    name: 'Lalitha Kumari',
    age: 34,
    gender: 'Female',
    phone: '7282828292',
    lastVisit: '05 May 2026',
    address: 'Dowleswaram, Temple Rd',
    bloodGroup: 'B-',
    disease: 'Ankle Sprain',
    registrationDate: '2026-06-05',
    chiefComplaint: 'Swelling and pain on lateral aspect of left ankle after misstepping yesterday.',
    allergies: 'Dust, Pollen',
    currentMedications: 'Tab. Zerodol-SP BD',
    pastMedicalHistory: 'None',
    photoUrl: 'https://api.dicebear.com/7.x/initials/svg?seed=Lalitha+Kumari'
  }
];
